default:
    @just --list

# Install tools and dependencies
init:
    go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.11.3

# Run tests
test:
    CGO_ENABLED=1 go test -v ./...

# Format code and apply lint fixes
fix:
    golangci-lint fmt

# Run linter
check:
    golangci-lint run --allow-parallel-runners
