// Code generated by telemetry/scripts/gen-helpers. DO NOT EDIT.
//
// EmitX helpers for the one-shot command_invoked variants. Each takes
// the gen'd XCommandInvokedProperties value, stamps the emit-side base
// fields (Command / DurationMs / InvokedBy / InvokedVia) on it, and
// dispatches via Client.fireCommandInvoked. Callers fill Outcome (and
// any variant-specific optional fields) at the call site.

package telemetry

import "context"

// EmitVersion fires command_invoked for `gaffer version`. No-op when ctx
// carries no Client (opt-out or unreadable config).
//
// Callers fill in Outcome (and any variant-specific optional
// fields). Command and DurationMs are stamped by the helper from
// Client state - any caller-set value is discarded.
func EmitVersion(ctx context.Context, p VersionCommandInvokedProperties) {
	c := ClientFromContext(ctx)
	if c == nil {
		return
	}
	c.stampInvocation(&p.Command, &p.DurationMs, &p.InvokedBy, &p.InvokedVia, CommandNameVersion)
	c.fireCommandInvoked(p)
}

// EmitInit fires command_invoked for `gaffer init`. No-op when ctx
// carries no Client (opt-out or unreadable config).
//
// Callers fill in Outcome (and any variant-specific optional
// fields). Command and DurationMs are stamped by the helper from
// Client state - any caller-set value is discarded.
func EmitInit(ctx context.Context, p InitCommandInvokedProperties) {
	c := ClientFromContext(ctx)
	if c == nil {
		return
	}
	c.stampInvocation(&p.Command, &p.DurationMs, &p.InvokedBy, &p.InvokedVia, CommandNameInit)
	c.fireCommandInvoked(p)
}

// EmitScaffold fires command_invoked for `gaffer scaffold`. No-op when ctx
// carries no Client (opt-out or unreadable config).
//
// Callers fill in Outcome (and any variant-specific optional
// fields). Command and DurationMs are stamped by the helper from
// Client state - any caller-set value is discarded.
func EmitScaffold(ctx context.Context, p ScaffoldCommandInvokedProperties) {
	c := ClientFromContext(ctx)
	if c == nil {
		return
	}
	c.stampInvocation(&p.Command, &p.DurationMs, &p.InvokedBy, &p.InvokedVia, CommandNameScaffold)
	c.fireCommandInvoked(p)
}

// EmitInfo fires command_invoked for `gaffer info`. No-op when ctx
// carries no Client (opt-out or unreadable config).
//
// Callers fill in Outcome (and any variant-specific optional
// fields). Command and DurationMs are stamped by the helper from
// Client state - any caller-set value is discarded.
func EmitInfo(ctx context.Context, p InfoCommandInvokedProperties) {
	c := ClientFromContext(ctx)
	if c == nil {
		return
	}
	c.stampInvocation(&p.Command, &p.DurationMs, &p.InvokedBy, &p.InvokedVia, CommandNameInfo)
	c.fireCommandInvoked(p)
}

// EmitManifest fires command_invoked for `gaffer manifest`. No-op when ctx
// carries no Client (opt-out or unreadable config).
//
// Callers fill in Outcome (and any variant-specific optional
// fields). Command and DurationMs are stamped by the helper from
// Client state - any caller-set value is discarded.
func EmitManifest(ctx context.Context, p ManifestCommandInvokedProperties) {
	c := ClientFromContext(ctx)
	if c == nil {
		return
	}
	c.stampInvocation(&p.Command, &p.DurationMs, &p.InvokedBy, &p.InvokedVia, CommandNameManifest)
	c.fireCommandInvoked(p)
}
