// Code generated by telemetry/scripts/gen-helpers. DO NOT EDIT.
//
// This file holds the wire types (Envelope, Context, per-event Properties,
// enums, RawCount) and the per-command Tx wrappers with typed setters.
// Runtime-free by design: no Client / ctx / panic-recover references, so
// the schema layer compiles in isolation. The public Begin / End / Emit
// helpers that bind to the runtime are generated into sibling files
// (tx.gen.go, emit.gen.go) which DO depend on the hand-written runtime
// (Client in telemetry.go, fireCommandInvoked / stampInvocation* in
// emit.go / tx.go).

package telemetry

import "encoding/json"

// UUID is a lowercase-hyphen UUID, no curly braces.
type UUID = string

// Timestamp is an RFC 3339 timestamp with millisecond precision.
type Timestamp = string

// SchemaVersion is the wire-schema version stamped on every envelope. Only
// bumped for breaking wire changes; additive changes keep the same version.
const SchemaVersion = "1"

// Event is the marker interface for every event type the generator emits.
// Implementations are closed by the unexported isEvent() method, so the
// Envelope.Events slice can hold any mix of generated event types but
// nothing from outside this package. Custom JSON unmarshal lives in a
// hand-written companion when an unmarshal path is needed.
type Event interface {
	isEvent()
}

// RawCount holds an unbucketed integer that bucket-rounds at marshal time to
// one of {0, 1, 2, 10, 100, 1000}. Producers store the raw count; the bucket
// math is applied at the JSON boundary so call sites never have to know the
// scheme.
type RawCount int

// MarshalJSON applies the bucket lookup: 0 / 1 / 2 / 10 / 100 / 1000 for the
// half-open intervals (-inf, 1) / [1, 2) / [2, 10) / [10, 100) / [100, 1000)
// / [1000, +inf). Negative values clamp to 0.
func (r RawCount) MarshalJSON() ([]byte, error) {
	switch n := int(r); {
	case n < 1:
		return []byte("0"), nil
	case n < 2:
		return []byte("1"), nil
	case n < 10:
		return []byte("2"), nil
	case n < 100:
		return []byte("10"), nil
	case n < 1000:
		return []byte("100"), nil
	default:
		return []byte("1000"), nil
	}
}

var _ json.Marshaler = RawCount(0)

// Emitter is a string enum mirroring the CUE definition.
type Emitter string

const (
	EmitterCLI    Emitter = "cli"
	EmitterMCP    Emitter = "mcp"
	EmitterVSCode Emitter = "vscode"
)

// OS is a string enum mirroring the CUE definition.
type OS string

const (
	OSDarwin  OS = "darwin"
	OSLinux   OS = "linux"
	OSWindows OS = "windows"
)

// Arch is a string enum mirroring the CUE definition.
type Arch string

const (
	ArchArm64 Arch = "arm64"
	ArchIA32  Arch = "ia32"
	ArchX64   Arch = "x64"
)

// RuntimeEnvironment is a string enum mirroring the CUE definition.
type RuntimeEnvironment string

const (
	RuntimeEnvironmentCI    RuntimeEnvironment = "ci"
	RuntimeEnvironmentLocal RuntimeEnvironment = "local"
)

// CommandName is a string enum mirroring the CUE definition.
type CommandName string

const (
	CommandNameDebug    CommandName = "debug"
	CommandNameDev      CommandName = "dev"
	CommandNameInfo     CommandName = "info"
	CommandNameInit     CommandName = "init"
	CommandNameLSP      CommandName = "lsp"
	CommandNameManifest CommandName = "manifest"
	CommandNameMCP      CommandName = "mcp"
	CommandNameScaffold CommandName = "scaffold"
	CommandNameVersion  CommandName = "version"
)

// Outcome is a string enum mirroring the CUE definition.
type Outcome string

const (
	OutcomeCaughtUp                 Outcome = "caught_up"
	OutcomeDAPProtocolError         Outcome = "dap_protocol_error"
	OutcomeDBConnectError           Outcome = "db_connect_error"
	OutcomeDBDisconnect             Outcome = "db_disconnect"
	OutcomeDBProtocolError          Outcome = "db_protocol_error"
	OutcomeFixtureExhausted         Outcome = "fixture_exhausted"
	OutcomeInternalError            Outcome = "internal_error"
	OutcomeLSPProtocolError         Outcome = "lsp_protocol_error"
	OutcomeManifestNotFound         Outcome = "manifest_not_found"
	OutcomeManifestParseError       Outcome = "manifest_parse_error"
	OutcomeManifestValidationError  Outcome = "manifest_validation_error"
	OutcomeMCPProtocolError         Outcome = "mcp_protocol_error"
	OutcomeProjectionEvalError      Outcome = "projection_eval_error"
	OutcomeProjectionOom            Outcome = "projection_oom"
	OutcomeProjectionParseError     Outcome = "projection_parse_error"
	OutcomeProjectionRangeError     Outcome = "projection_range_error"
	OutcomeProjectionReferenceError Outcome = "projection_reference_error"
	OutcomeProjectionStackOverflow  Outcome = "projection_stack_overflow"
	OutcomeProjectionSyntaxError    Outcome = "projection_syntax_error"
	OutcomeProjectionTypeError      Outcome = "projection_type_error"
	OutcomeProjectionUnknownError   Outcome = "projection_unknown_error"
	OutcomeProjectionURIError       Outcome = "projection_uri_error"
	OutcomeProjectionUserThrow      Outcome = "projection_user_throw"
	OutcomeSuccess                  Outcome = "success"
	OutcomeUserError                Outcome = "user_error"
	OutcomeUserInterrupt            Outcome = "user_interrupt"
)

// ProjectionOutcome is a string enum mirroring the CUE definition.
type ProjectionOutcome string

const (
	ProjectionOutcomeProjectionEvalError      ProjectionOutcome = "projection_eval_error"
	ProjectionOutcomeProjectionOom            ProjectionOutcome = "projection_oom"
	ProjectionOutcomeProjectionParseError     ProjectionOutcome = "projection_parse_error"
	ProjectionOutcomeProjectionRangeError     ProjectionOutcome = "projection_range_error"
	ProjectionOutcomeProjectionReferenceError ProjectionOutcome = "projection_reference_error"
	ProjectionOutcomeProjectionStackOverflow  ProjectionOutcome = "projection_stack_overflow"
	ProjectionOutcomeProjectionSyntaxError    ProjectionOutcome = "projection_syntax_error"
	ProjectionOutcomeProjectionTypeError      ProjectionOutcome = "projection_type_error"
	ProjectionOutcomeProjectionUnknownError   ProjectionOutcome = "projection_unknown_error"
	ProjectionOutcomeProjectionURIError       ProjectionOutcome = "projection_uri_error"
	ProjectionOutcomeProjectionUserThrow      ProjectionOutcome = "projection_user_throw"
)

// InvokedBy is a string enum mirroring the CUE definition.
type InvokedBy string

const (
	InvokedByDirect    InvokedBy = "direct"
	InvokedByMCPClient InvokedBy = "mcp_client"
	InvokedByVSCode    InvokedBy = "vscode"
)

// InvokedVia is a string enum mirroring the CUE definition.
type InvokedVia string

const (
	InvokedViaCodeLens       InvokedVia = "code_lens"
	InvokedViaCommandPalette InvokedVia = "command_palette"
	InvokedViaMCPProvider    InvokedVia = "mcp_provider"
	InvokedViaStdio          InvokedVia = "stdio"
	InvokedViaTerminal       InvokedVia = "terminal"
)

// Editor is a string enum mirroring the CUE definition.
type Editor string

const (
	EditorCursor   Editor = "cursor"
	EditorOther    Editor = "other"
	EditorVSCode   Editor = "vscode"
	EditorVSCodium Editor = "vscodium"
	EditorWindsurf Editor = "windsurf"
)

// CLIUnreachableReason is a string enum mirroring the CUE definition.
type CLIUnreachableReason string

const (
	CLIUnreachableReasonBinaryNotFound    CLIUnreachableReason = "binary_not_found"
	CLIUnreachableReasonBinarySpawnFailed CLIUnreachableReason = "binary_spawn_failed"
	CLIUnreachableReasonTimeout           CLIUnreachableReason = "timeout"
	CLIUnreachableReasonUnknownError      CLIUnreachableReason = "unknown_error"
)

// ExceptionPhase is a string enum mirroring the CUE definition.
type ExceptionPhase string

const (
	ExceptionPhaseEventProcessing ExceptionPhase = "event_processing"
	ExceptionPhaseProjectionInit  ExceptionPhase = "projection_init"
	ExceptionPhaseShutdown        ExceptionPhase = "shutdown"
	ExceptionPhaseStartup         ExceptionPhase = "startup"
)

// FileSizeBucket is an int enum mirroring the CUE definition.
type FileSizeBucket int

const (
	FileSizeBucketUnder1KB  FileSizeBucket = 0
	FileSizeBucket1To5KB    FileSizeBucket = 1024
	FileSizeBucket5To20KB   FileSizeBucket = 5120
	FileSizeBucket20To100KB FileSizeBucket = 20480
	FileSizeBucketOver100KB FileSizeBucket = 102400
)

// Envelope is the top-level shape POSTed to the telemetry worker. One
// envelope per HTTP request, carrying a batch of events that share the same
// emitter and run.
type Envelope struct {
	// Bumped only for breaking wire changes; additive changes keep the same version.
	SchemaVersion string `json:"schema_version"`
	// Per-install random UUID identifying this gaffer installation.
	EmitterID UUID `json:"emitter_id"`
	// Per-process UUID identifying a single CLI invocation or extension activation. Correlates events emitted from the same process.
	RunID   UUID    `json:"run_id"`
	Context Context `json:"context"`
	Events  []Event `json:"events"`
}

// Context is per-envelope metadata describing the emitting environment.
// Identical for every event in a batch.
type Context struct {
	Emitter Emitter `json:"emitter"`
	// Gaffer release version (semver).
	LibVersion         string             `json:"lib_version"`
	OS                 OS                 `json:"os"`
	Arch               Arch               `json:"arch"`
	RuntimeEnvironment RuntimeEnvironment `json:"runtime_environment"`
	// Salted hash of the project root absolute path - sha256(salt || abs-project-root)[:16]. Lets us distinguish one user with five projects from five users with one project. The path itself never leaves the machine. Absent for invocations that didn't run inside a project (e.g. `gaffer version`).
	ProjectID *string `json:"project_id,omitempty"`
	// Spawn-time identity link. Set when an extension spawns a CLI process, populated with the spawning extension's emitter_id (parsed from the --invoker-id flag).
	InvokerID *UUID `json:"invoker_id,omitempty"`
}

// CommandInvoked fires once at the end of every CLI invocation - one-shot or
// long-running. The wire shape carries a discriminated union of variant
// property structs in `properties`; Go can't express that directly, so the
// field is `any` and producers assign the per-variant struct
// (VersionCommandInvokedProperties, DevCommandInvokedProperties, ...) they
// built up via the matching Tx.
type CommandInvoked struct {
	Name       string    `json:"name"`
	Timestamp  Timestamp `json:"timestamp"`
	Properties any       `json:"properties"`
}

func (CommandInvoked) isEvent() {}

// CommandInvokedProperties holds the base fields present on every variant
// of command_invoked. Kept as a standalone type for documentation /
// shape reference; per-command variants inline these fields directly
// rather than embedding so call sites stay flat (no nested struct
// literal required to set Outcome).
type CommandInvokedProperties struct {
	// Which gaffer command ran. Variants narrow this to a specific literal.
	Command CommandName `json:"command"`
	// Wall-clock duration from process start to exit. For long-running commands (`dev`, `mcp`, `lsp`, `debug`) this is invocation lifetime, not engagement time - includes idle stretches where the editor was open but nobody was touching gaffer.
	DurationMs RawCount `json:"duration_ms"`
	// What ended the invocation.
	Outcome Outcome `json:"outcome"`
	// Who triggered the run.
	InvokedBy InvokedBy `json:"invoked_by"`
	// Specific surface the invocation came through.
	InvokedVia InvokedVia `json:"invoked_via"`
}

// VersionCommandInvokedProperties carries the property set for `gaffer version`.
// Base fields are inlined rather than embedded so callers can set
// Outcome (and future per-invocation overrides) at the top-level
// struct literal without an extra nesting layer.
type VersionCommandInvokedProperties struct {
	// Which gaffer command ran. Variants narrow this to a specific literal.
	Command CommandName `json:"command"`
	// Wall-clock duration from process start to exit. For long-running commands (`dev`, `mcp`, `lsp`, `debug`) this is invocation lifetime, not engagement time - includes idle stretches where the editor was open but nobody was touching gaffer.
	DurationMs RawCount `json:"duration_ms"`
	// What ended the invocation.
	Outcome Outcome `json:"outcome"`
	// Who triggered the run.
	InvokedBy InvokedBy `json:"invoked_by"`
	// Specific surface the invocation came through.
	InvokedVia InvokedVia `json:"invoked_via"`
}

// InitCommandInvokedProperties carries the property set for `gaffer init`.
// Base fields are inlined rather than embedded so callers can set
// Outcome (and future per-invocation overrides) at the top-level
// struct literal without an extra nesting layer.
type InitCommandInvokedProperties struct {
	// Which gaffer command ran. Variants narrow this to a specific literal.
	Command CommandName `json:"command"`
	// Wall-clock duration from process start to exit. For long-running commands (`dev`, `mcp`, `lsp`, `debug`) this is invocation lifetime, not engagement time - includes idle stretches where the editor was open but nobody was touching gaffer.
	DurationMs RawCount `json:"duration_ms"`
	// What ended the invocation.
	Outcome Outcome `json:"outcome"`
	// Who triggered the run.
	InvokedBy InvokedBy `json:"invoked_by"`
	// Specific surface the invocation came through.
	InvokedVia InvokedVia `json:"invoked_via"`
}

// ScaffoldCommandInvokedProperties carries the property set for `gaffer scaffold`.
// Base fields are inlined rather than embedded so callers can set
// Outcome (and future per-invocation overrides) at the top-level
// struct literal without an extra nesting layer.
type ScaffoldCommandInvokedProperties struct {
	// Which gaffer command ran. Variants narrow this to a specific literal.
	Command CommandName `json:"command"`
	// Wall-clock duration from process start to exit. For long-running commands (`dev`, `mcp`, `lsp`, `debug`) this is invocation lifetime, not engagement time - includes idle stretches where the editor was open but nobody was touching gaffer.
	DurationMs RawCount `json:"duration_ms"`
	// What ended the invocation.
	Outcome Outcome `json:"outcome"`
	// Who triggered the run.
	InvokedBy InvokedBy `json:"invoked_by"`
	// Specific surface the invocation came through.
	InvokedVia InvokedVia `json:"invoked_via"`
}

// InfoCommandInvokedProperties carries the property set for `gaffer info`.
// Base fields are inlined rather than embedded so callers can set
// Outcome (and future per-invocation overrides) at the top-level
// struct literal without an extra nesting layer.
type InfoCommandInvokedProperties struct {
	// Which gaffer command ran. Variants narrow this to a specific literal.
	Command CommandName `json:"command"`
	// Wall-clock duration from process start to exit. For long-running commands (`dev`, `mcp`, `lsp`, `debug`) this is invocation lifetime, not engagement time - includes idle stretches where the editor was open but nobody was touching gaffer.
	DurationMs RawCount `json:"duration_ms"`
	// What ended the invocation.
	Outcome Outcome `json:"outcome"`
	// Who triggered the run.
	InvokedBy InvokedBy `json:"invoked_by"`
	// Specific surface the invocation came through.
	InvokedVia InvokedVia `json:"invoked_via"`
}

// ManifestCommandInvokedProperties carries the property set for `gaffer manifest`.
// Base fields are inlined rather than embedded so callers can set
// Outcome (and future per-invocation overrides) at the top-level
// struct literal without an extra nesting layer.
type ManifestCommandInvokedProperties struct {
	// Which gaffer command ran. Variants narrow this to a specific literal.
	Command CommandName `json:"command"`
	// Wall-clock duration from process start to exit. For long-running commands (`dev`, `mcp`, `lsp`, `debug`) this is invocation lifetime, not engagement time - includes idle stretches where the editor was open but nobody was touching gaffer.
	DurationMs RawCount `json:"duration_ms"`
	// What ended the invocation.
	Outcome Outcome `json:"outcome"`
	// Who triggered the run.
	InvokedBy InvokedBy `json:"invoked_by"`
	// Specific surface the invocation came through.
	InvokedVia InvokedVia `json:"invoked_via"`
	// Top-level manifest section names present (e.g. ["projections", "fixtures"]). Section *presence* only, never contents.
	ManifestFeaturesUsed []string `json:"manifest_features_used,omitempty"`
	// Bucketed count from manifest.
	ProjectionCount *RawCount `json:"projection_count,omitempty"`
	// Bucketed count from manifest.
	FixtureCount *RawCount `json:"fixture_count,omitempty"`
}

// DevCommandInvokedProperties carries the property set for `gaffer dev`.
// Base fields are inlined rather than embedded so callers can set
// Outcome (and future per-invocation overrides) at the top-level
// struct literal without an extra nesting layer.
type DevCommandInvokedProperties struct {
	// Which gaffer command ran. Variants narrow this to a specific literal.
	Command CommandName `json:"command"`
	// Wall-clock duration from process start to exit. For long-running commands (`dev`, `mcp`, `lsp`, `debug`) this is invocation lifetime, not engagement time - includes idle stretches where the editor was open but nobody was touching gaffer.
	DurationMs RawCount `json:"duration_ms"`
	// What ended the invocation.
	Outcome Outcome `json:"outcome"`
	// Who triggered the run.
	InvokedBy InvokedBy `json:"invoked_by"`
	// Specific surface the invocation came through.
	InvokedVia InvokedVia `json:"invoked_via"`
	// Top-level manifest section names present.
	ManifestFeaturesUsed []string `json:"manifest_features_used,omitempty"`
	// Bucketed count from manifest.
	ProjectionCount *RawCount `json:"projection_count,omitempty"`
	// Bucketed count from manifest.
	FixtureCount *RawCount `json:"fixture_count,omitempty"`
	// Whether a live KurrentDB connection was requested.
	ConnectedToDB *bool `json:"connected_to_db,omitempty"`
	// Major.minor of the connected server (e.g. "26.1", "27.0") truncated from the full server `/info` version string, or "unknown" if it was unparseable. Absent when not connected.
	DBVersion *string `json:"db_version,omitempty"`
	// Distinct, sorted set of `projection_*` outcome values seen during the run. Empty when none.
	ProjectionErrorsSeen []ProjectionOutcome `json:"projection_errors_seen,omitempty"`
}

// DevTx accumulates `dev` command properties over the lifetime of the
// invocation. Single-goroutine-owned: setters are NOT safe for concurrent use -
// drain counters on the main goroutine before End() time.
type DevTx struct {
	props DevCommandInvokedProperties
}

// Properties returns a snapshot of the accumulated properties for marshal.
func (tx *DevTx) Properties() DevCommandInvokedProperties { return tx.props }

// SetOutcome records the final outcome for the invocation.
// Nil-safe: silent no-op on a nil receiver.
func (tx *DevTx) SetOutcome(o Outcome) {
	if tx == nil {
		return
	}
	tx.props.Outcome = o
}

// SetManifestFeaturesUsed records manifest_features_used. Top-level manifest section names present. Nil-safe: silent no-op on a nil receiver.
func (tx *DevTx) SetManifestFeaturesUsed(v []string) {
	if tx == nil {
		return
	}
	tx.props.ManifestFeaturesUsed = v
}

// SetProjectionCount records projection_count. Bucketed count from manifest. Nil-safe: silent no-op on a nil receiver.
func (tx *DevTx) SetProjectionCount(n int) {
	if tx == nil {
		return
	}
	v := RawCount(n)
	tx.props.ProjectionCount = &v
}

// SetFixtureCount records fixture_count. Bucketed count from manifest. Nil-safe: silent no-op on a nil receiver.
func (tx *DevTx) SetFixtureCount(n int) {
	if tx == nil {
		return
	}
	v := RawCount(n)
	tx.props.FixtureCount = &v
}

// SetConnectedToDB records connected_to_db. Whether a live KurrentDB connection was requested. Nil-safe: silent no-op on a nil receiver.
func (tx *DevTx) SetConnectedToDB(b bool) {
	if tx == nil {
		return
	}
	tx.props.ConnectedToDB = &b
}

// SetDBVersion records db_version. Major.minor of the connected server (e.g. "26.1", "27.0") truncated from the full server `/info` version string, or "unknown" if it was unparseable. Absent when not connected. Nil-safe: silent no-op on a nil receiver.
func (tx *DevTx) SetDBVersion(s string) {
	if tx == nil {
		return
	}
	tx.props.DBVersion = &s
}

// SetProjectionErrorsSeen records projection_errors_seen. Distinct, sorted set of `projection_*` outcome values seen during the run. Empty when none. Nil-safe: silent no-op on a nil receiver.
func (tx *DevTx) SetProjectionErrorsSeen(v []ProjectionOutcome) {
	if tx == nil {
		return
	}
	tx.props.ProjectionErrorsSeen = v
}

// MCPCommandInvokedProperties carries the property set for `gaffer mcp`.
// Base fields are inlined rather than embedded so callers can set
// Outcome (and future per-invocation overrides) at the top-level
// struct literal without an extra nesting layer.
type MCPCommandInvokedProperties struct {
	// Which gaffer command ran. Variants narrow this to a specific literal.
	Command CommandName `json:"command"`
	// Wall-clock duration from process start to exit. For long-running commands (`dev`, `mcp`, `lsp`, `debug`) this is invocation lifetime, not engagement time - includes idle stretches where the editor was open but nobody was touching gaffer.
	DurationMs RawCount `json:"duration_ms"`
	// What ended the invocation.
	Outcome Outcome `json:"outcome"`
	// Who triggered the run.
	InvokedBy InvokedBy `json:"invoked_by"`
	// Specific surface the invocation came through.
	InvokedVia InvokedVia `json:"invoked_via"`
	// Top-level manifest section names present.
	ManifestFeaturesUsed []string `json:"manifest_features_used,omitempty"`
	// Bucketed. Total tool invocations across the session.
	ToolCallCount *RawCount `json:"tool_call_count,omitempty"`
	// Bucketed. Total resource reads across the session.
	ResourceReadCount *RawCount `json:"resource_read_count,omitempty"`
	// Distinct, sorted set of `projection_*` outcome values seen during the session. Empty when none.
	ProjectionErrorsSeen []ProjectionOutcome `json:"projection_errors_seen,omitempty"`
}

// MCPTx accumulates `mcp` command properties over the lifetime of the
// invocation. Single-goroutine-owned: setters are NOT safe for concurrent use -
// drain counters on the main goroutine before End() time.
type MCPTx struct {
	props MCPCommandInvokedProperties
}

// Properties returns a snapshot of the accumulated properties for marshal.
func (tx *MCPTx) Properties() MCPCommandInvokedProperties { return tx.props }

// SetOutcome records the final outcome for the invocation.
// Nil-safe: silent no-op on a nil receiver.
func (tx *MCPTx) SetOutcome(o Outcome) {
	if tx == nil {
		return
	}
	tx.props.Outcome = o
}

// SetManifestFeaturesUsed records manifest_features_used. Top-level manifest section names present. Nil-safe: silent no-op on a nil receiver.
func (tx *MCPTx) SetManifestFeaturesUsed(v []string) {
	if tx == nil {
		return
	}
	tx.props.ManifestFeaturesUsed = v
}

// SetToolCallCount records tool_call_count. Bucketed. Total tool invocations across the session. Nil-safe: silent no-op on a nil receiver.
func (tx *MCPTx) SetToolCallCount(n int) {
	if tx == nil {
		return
	}
	v := RawCount(n)
	tx.props.ToolCallCount = &v
}

// SetResourceReadCount records resource_read_count. Bucketed. Total resource reads across the session. Nil-safe: silent no-op on a nil receiver.
func (tx *MCPTx) SetResourceReadCount(n int) {
	if tx == nil {
		return
	}
	v := RawCount(n)
	tx.props.ResourceReadCount = &v
}

// SetProjectionErrorsSeen records projection_errors_seen. Distinct, sorted set of `projection_*` outcome values seen during the session. Empty when none. Nil-safe: silent no-op on a nil receiver.
func (tx *MCPTx) SetProjectionErrorsSeen(v []ProjectionOutcome) {
	if tx == nil {
		return
	}
	tx.props.ProjectionErrorsSeen = v
}

// LSPCommandInvokedProperties carries the property set for `gaffer lsp`.
// Base fields are inlined rather than embedded so callers can set
// Outcome (and future per-invocation overrides) at the top-level
// struct literal without an extra nesting layer.
type LSPCommandInvokedProperties struct {
	// Which gaffer command ran. Variants narrow this to a specific literal.
	Command CommandName `json:"command"`
	// Wall-clock duration from process start to exit. For long-running commands (`dev`, `mcp`, `lsp`, `debug`) this is invocation lifetime, not engagement time - includes idle stretches where the editor was open but nobody was touching gaffer.
	DurationMs RawCount `json:"duration_ms"`
	// What ended the invocation.
	Outcome Outcome `json:"outcome"`
	// Who triggered the run.
	InvokedBy InvokedBy `json:"invoked_by"`
	// Specific surface the invocation came through.
	InvokedVia InvokedVia `json:"invoked_via"`
	// Bucketed total code-lens requests served.
	CodeLensRequestCount *RawCount `json:"code_lens_request_count,omitempty"`
	// Bucketed total diagnostic publishes.
	DiagnosticPublishCount *RawCount `json:"diagnostic_publish_count,omitempty"`
}

// LSPTx accumulates `lsp` command properties over the lifetime of the
// invocation. Single-goroutine-owned: setters are NOT safe for concurrent use -
// drain counters on the main goroutine before End() time.
type LSPTx struct {
	props LSPCommandInvokedProperties
}

// Properties returns a snapshot of the accumulated properties for marshal.
func (tx *LSPTx) Properties() LSPCommandInvokedProperties { return tx.props }

// SetOutcome records the final outcome for the invocation.
// Nil-safe: silent no-op on a nil receiver.
func (tx *LSPTx) SetOutcome(o Outcome) {
	if tx == nil {
		return
	}
	tx.props.Outcome = o
}

// SetCodeLensRequestCount records code_lens_request_count. Bucketed total code-lens requests served. Nil-safe: silent no-op on a nil receiver.
func (tx *LSPTx) SetCodeLensRequestCount(n int) {
	if tx == nil {
		return
	}
	v := RawCount(n)
	tx.props.CodeLensRequestCount = &v
}

// SetDiagnosticPublishCount records diagnostic_publish_count. Bucketed total diagnostic publishes. Nil-safe: silent no-op on a nil receiver.
func (tx *LSPTx) SetDiagnosticPublishCount(n int) {
	if tx == nil {
		return
	}
	v := RawCount(n)
	tx.props.DiagnosticPublishCount = &v
}

// DebugCommandInvokedProperties carries the property set for `gaffer debug`.
// Base fields are inlined rather than embedded so callers can set
// Outcome (and future per-invocation overrides) at the top-level
// struct literal without an extra nesting layer.
type DebugCommandInvokedProperties struct {
	// Which gaffer command ran. Variants narrow this to a specific literal.
	Command CommandName `json:"command"`
	// Wall-clock duration from process start to exit. For long-running commands (`dev`, `mcp`, `lsp`, `debug`) this is invocation lifetime, not engagement time - includes idle stretches where the editor was open but nobody was touching gaffer.
	DurationMs RawCount `json:"duration_ms"`
	// What ended the invocation.
	Outcome Outcome `json:"outcome"`
	// Who triggered the run.
	InvokedBy InvokedBy `json:"invoked_by"`
	// Specific surface the invocation came through.
	InvokedVia InvokedVia `json:"invoked_via"`
	// Bucketed. Initial breakpoints set by the client.
	BreakpointCount *RawCount `json:"breakpoint_count,omitempty"`
	// Bucketed. Total step requests served.
	StepCount *RawCount `json:"step_count,omitempty"`
	// Bucketed. Times the session paused (breakpoint or pause request).
	PauseCount *RawCount `json:"pause_count,omitempty"`
	// Bucketed. DAP restarts.
	RestartCount *RawCount `json:"restart_count,omitempty"`
	// Bucketed. Events fed from the fixture.
	FixtureEventCount *RawCount `json:"fixture_event_count,omitempty"`
	// Distinct, sorted set of `projection_*` outcome values seen during the session. Empty when none.
	ProjectionErrorsSeen []ProjectionOutcome `json:"projection_errors_seen,omitempty"`
}

// DebugTx accumulates `debug` command properties over the lifetime of the
// invocation. Single-goroutine-owned: setters are NOT safe for concurrent use -
// drain counters on the main goroutine before End() time.
type DebugTx struct {
	props DebugCommandInvokedProperties
}

// Properties returns a snapshot of the accumulated properties for marshal.
func (tx *DebugTx) Properties() DebugCommandInvokedProperties { return tx.props }

// SetOutcome records the final outcome for the invocation.
// Nil-safe: silent no-op on a nil receiver.
func (tx *DebugTx) SetOutcome(o Outcome) {
	if tx == nil {
		return
	}
	tx.props.Outcome = o
}

// SetBreakpointCount records breakpoint_count. Bucketed. Initial breakpoints set by the client. Nil-safe: silent no-op on a nil receiver.
func (tx *DebugTx) SetBreakpointCount(n int) {
	if tx == nil {
		return
	}
	v := RawCount(n)
	tx.props.BreakpointCount = &v
}

// SetStepCount records step_count. Bucketed. Total step requests served. Nil-safe: silent no-op on a nil receiver.
func (tx *DebugTx) SetStepCount(n int) {
	if tx == nil {
		return
	}
	v := RawCount(n)
	tx.props.StepCount = &v
}

// SetPauseCount records pause_count. Bucketed. Times the session paused (breakpoint or pause request). Nil-safe: silent no-op on a nil receiver.
func (tx *DebugTx) SetPauseCount(n int) {
	if tx == nil {
		return
	}
	v := RawCount(n)
	tx.props.PauseCount = &v
}

// SetRestartCount records restart_count. Bucketed. DAP restarts. Nil-safe: silent no-op on a nil receiver.
func (tx *DebugTx) SetRestartCount(n int) {
	if tx == nil {
		return
	}
	v := RawCount(n)
	tx.props.RestartCount = &v
}

// SetFixtureEventCount records fixture_event_count. Bucketed. Events fed from the fixture. Nil-safe: silent no-op on a nil receiver.
func (tx *DebugTx) SetFixtureEventCount(n int) {
	if tx == nil {
		return
	}
	v := RawCount(n)
	tx.props.FixtureEventCount = &v
}

// SetProjectionErrorsSeen records projection_errors_seen. Distinct, sorted set of `projection_*` outcome values seen during the session. Empty when none. Nil-safe: silent no-op on a nil receiver.
func (tx *DebugTx) SetProjectionErrorsSeen(v []ProjectionOutcome) {
	if tx == nil {
		return
	}
	tx.props.ProjectionErrorsSeen = v
}

// ProjectionShape carries a snapshot of what a projection's source looks
// like, structurally. Emitted on first encounter and again whenever the
// bucketed shape drifts.
type ProjectionShape struct {
	Name       string                    `json:"name"`
	Timestamp  Timestamp                 `json:"timestamp"`
	Properties ProjectionShapeProperties `json:"properties"`
}

func (ProjectionShape) isEvent() {}

// ProjectionShapeProperties holds the property fields for the projection_shape event.
type ProjectionShapeProperties struct {
	// Per-install hashed id: sha256(salt || projection_relative_path)[:16]. Stable across processes for the same projection. 16 hex chars.
	ProjectionID string `json:"projection_id"`
	// True when the AST parser succeeded. False = parser error; the `handlers` and `builtin_counts` data are best-effort partial.
	Parsable bool `json:"parsable"`
	// Bucketed file size on disk in bytes.
	FileSize FileSizeBucket `json:"file_size"`
	// Which handlers the projection registers.
	Handlers ProjectionShapeHandlers `json:"handlers"`
	// Bucketed call counts per allowlisted projection builtin. Sparse - a builtin not called is absent. Keys are the JS API names verbatim. Adding a new builtin to gaffer means adding it here, the AST walker, and the deprecation-diagnostic visitor in the same PR.
	BuiltinCounts ProjectionShapeBuiltinCounts `json:"builtin_counts"`
}

// ProjectionShapeHandlers is the per-handler-kind set the projection registers.
type ProjectionShapeHandlers struct {
	// `$any` handler registered.
	Any bool `json:"any"`
	// `$init` or `$initShared` handler registered.
	Init bool `json:"init"`
	// `$deleted` handler registered.
	Deleted bool `json:"deleted"`
	// Bucketed count of distinct event-name handlers (i.e. those other than `$any`, `$init`, `$deleted`). Names themselves are never sent.
	DistinctEventNames RawCount `json:"distinct_event_names"`
}

// ProjectionShapeBuiltinCounts holds bucketed call counts for the allowlisted
// projection builtins. Sparse: a builtin not called is absent in JSON.
type ProjectionShapeBuiltinCounts struct {
	FromAll        *RawCount `json:"fromAll,omitempty"`
	FromStream     *RawCount `json:"fromStream,omitempty"`
	FromStreams    *RawCount `json:"fromStreams,omitempty"`
	FromCategory   *RawCount `json:"fromCategory,omitempty"`
	FromCategories *RawCount `json:"fromCategories,omitempty"`
	When           *RawCount `json:"when,omitempty"`
	ForeachStream  *RawCount `json:"foreachStream,omitempty"`
	OutputState    *RawCount `json:"outputState,omitempty"`
	TransformBy    *RawCount `json:"transformBy,omitempty"`
	PartitionBy    *RawCount `json:"partitionBy,omitempty"`
	Emit           *RawCount `json:"emit,omitempty"`
	LinkTo         *RawCount `json:"linkTo,omitempty"`
	CopyTo         *RawCount `json:"copyTo,omitempty"`
	// deprecated.
	LinkStreamTo  *RawCount `json:"linkStreamTo,omitempty"`
	ChainHandlers *RawCount `json:"chainHandlers,omitempty"`
	UpdateOf      *RawCount `json:"updateOf,omitempty"`
}

// ExtensionActivated fires once on extension activation. The one event that
// can fire when gaffer is otherwise unable to run - used to detect broken
// installs.
type ExtensionActivated struct {
	Name       string                       `json:"name"`
	Timestamp  Timestamp                    `json:"timestamp"`
	Properties ExtensionActivatedProperties `json:"properties"`
}

func (ExtensionActivated) isEvent() {}

// ExtensionActivatedProperties holds the property fields for the extension_activated event.
type ExtensionActivatedProperties struct {
	Editor Editor `json:"editor"`
	// Editor version string (e.g. "1.95.2").
	EditorVersion string `json:"editor_version"`
	// Whether the gaffer CLI binary was reachable on activation (PATH-resolvable + spawnable + responded to `gaffer version` within timeout).
	CLIReachable bool `json:"cli_reachable"`
	// Set when `cli_reachable = false`; absent otherwise.
	CLIUnreachableReason *CLIUnreachableReason `json:"cli_unreachable_reason,omitempty"`
	// Bucketed major.minor of the CLI binary's reported version. Present when `cli_reachable = true`.
	CLIVersion *string `json:"cli_version,omitempty"`
	// Time from extension activation to first event-emit decision.
	ActivationDurationMs RawCount `json:"activation_duration_ms"`
}

// Exception captures gaffer-side crashes only - Go panics in the CLI / MCP,
// unhandled JS errors in the extension host, runtime exceptions in our own
// .NET code. Projection runtime errors surface as `outcome` on the relevant
// `command_invoked` event instead.
type Exception struct {
	Name       string              `json:"name"`
	Timestamp  Timestamp           `json:"timestamp"`
	Properties ExceptionProperties `json:"properties"`
}

func (Exception) isEvent() {}

// ExceptionProperties holds the property fields for the exception event.
type ExceptionProperties struct {
	// Causal chain of exceptions, outer wrapper first, root cause last.
	Exceptions []ExceptionEntry `json:"exceptions"`
	// The CLI command that was running, if any. May be absent when the crash happens before command dispatch.
	Command *CommandName `json:"command,omitempty"`
	// Coarse lifecycle bucket the crash happened in.
	Phase ExceptionPhase `json:"phase"`
}

// ExceptionEntry is one exception in the causal chain.
type ExceptionEntry struct {
	// Exception type name (e.g. "RuntimeError", "TypeError").
	Type string `json:"type"`
	// Exception message. ONLY ever a message gaffer wrote - never a Jint or FFI-bubbled message that could embed user identifiers, source snippets, or function names from user code.
	Value string `json:"value"`
	// True for gaffer-owned code; false for stdlib / vendored deps.
	InApp bool `json:"in_app"`
	// Stack frames. User-JS frames are dropped entirely; remaining frames carry basename + function + line.
	Stacktrace ExceptionStacktrace `json:"stacktrace"`
}

// ExceptionStacktrace is the structured stacktrace shape on every entry.
type ExceptionStacktrace struct {
	Type   string  `json:"type"`
	Frames []Frame `json:"frames"`
}

// Frame is one stack frame after structural scrubbing.
type Frame struct {
	// File basename only (never full path).
	Filename string `json:"filename"`
	// Function name. May be absent for anonymous frames.
	Function *string `json:"function,omitempty"`
	// 1-indexed line number in the source. May be absent if unknown.
	Lineno *int `json:"lineno,omitempty"`
	// True for gaffer-owned code, false for stdlib / vendored deps.
	InApp bool `json:"in_app"`
}
