// Code generated by telemetry/scripts/gen-helpers. DO NOT EDIT.
//
// Begin / End helpers for the long-running command_invoked variants.
// Binds the gen'd Tx types (declared in events.gen.go) to the runtime in
// this package: Client lookup via ClientFromContext, base-field stamping
// via stampInvocationBase, sink dispatch via Client.fireCommandInvoked.
// See doc.go for the End() defer-direct contract and outcome cascade.

package telemetry

import "context"

// BeginDev opens a Dev command_invoked transaction. Stash the
// returned Tx and `defer tx.End(ctx)` at the top of the cobra RunE.
// Returns nil when ctx carries no Client (opt-out or unreadable
// config); End is nil-safe so callers don't need to branch on the
// return.
//
// See doc.go for the End() defer-direct contract.
func BeginDev(ctx context.Context) *DevTx {
	if ClientFromContext(ctx) == nil {
		return nil
	}
	return &DevTx{}
}

// End finalises the dev transaction: recovers any in-flight panic,
// stamps the emit-side base fields on tx.props, defaults Outcome
// from (recovered panic | ctx.Err() | success), enqueues the
// envelope, and re-panics if the command body panicked.
//
// MUST be called as `defer tx.End(ctx)` directly - see doc.go for
// the load-bearing recover-frame requirement.
func (tx *DevTx) End(ctx context.Context) {
	r := recover()
	defer func() {
		if r != nil {
			panic(r)
		}
	}()
	if tx == nil {
		return
	}
	c := ClientFromContext(ctx)
	if c == nil {
		return
	}
	stampInvocationBase(&tx.props.Command, &tx.props.DurationMs, &tx.props.Outcome, &tx.props.InvokedBy, &tx.props.InvokedVia, c.startTime, CommandNameDev, ctx, r)
	c.fireCommandInvoked(tx.props)
}

// BeginMCP opens an MCP command_invoked transaction. Stash the
// returned Tx and `defer tx.End(ctx)` at the top of the cobra RunE.
// Returns nil when ctx carries no Client (opt-out or unreadable
// config); End is nil-safe so callers don't need to branch on the
// return.
//
// See doc.go for the End() defer-direct contract.
func BeginMCP(ctx context.Context) *MCPTx {
	if ClientFromContext(ctx) == nil {
		return nil
	}
	return &MCPTx{}
}

// End finalises the mcp transaction: recovers any in-flight panic,
// stamps the emit-side base fields on tx.props, defaults Outcome
// from (recovered panic | ctx.Err() | success), enqueues the
// envelope, and re-panics if the command body panicked.
//
// MUST be called as `defer tx.End(ctx)` directly - see doc.go for
// the load-bearing recover-frame requirement.
func (tx *MCPTx) End(ctx context.Context) {
	r := recover()
	defer func() {
		if r != nil {
			panic(r)
		}
	}()
	if tx == nil {
		return
	}
	c := ClientFromContext(ctx)
	if c == nil {
		return
	}
	stampInvocationBase(&tx.props.Command, &tx.props.DurationMs, &tx.props.Outcome, &tx.props.InvokedBy, &tx.props.InvokedVia, c.startTime, CommandNameMCP, ctx, r)
	c.fireCommandInvoked(tx.props)
}

// BeginLSP opens an LSP command_invoked transaction. Stash the
// returned Tx and `defer tx.End(ctx)` at the top of the cobra RunE.
// Returns nil when ctx carries no Client (opt-out or unreadable
// config); End is nil-safe so callers don't need to branch on the
// return.
//
// See doc.go for the End() defer-direct contract.
func BeginLSP(ctx context.Context) *LSPTx {
	if ClientFromContext(ctx) == nil {
		return nil
	}
	return &LSPTx{}
}

// End finalises the lsp transaction: recovers any in-flight panic,
// stamps the emit-side base fields on tx.props, defaults Outcome
// from (recovered panic | ctx.Err() | success), enqueues the
// envelope, and re-panics if the command body panicked.
//
// MUST be called as `defer tx.End(ctx)` directly - see doc.go for
// the load-bearing recover-frame requirement.
func (tx *LSPTx) End(ctx context.Context) {
	r := recover()
	defer func() {
		if r != nil {
			panic(r)
		}
	}()
	if tx == nil {
		return
	}
	c := ClientFromContext(ctx)
	if c == nil {
		return
	}
	stampInvocationBase(&tx.props.Command, &tx.props.DurationMs, &tx.props.Outcome, &tx.props.InvokedBy, &tx.props.InvokedVia, c.startTime, CommandNameLSP, ctx, r)
	c.fireCommandInvoked(tx.props)
}

// BeginDebug opens a Debug command_invoked transaction. Stash the
// returned Tx and `defer tx.End(ctx)` at the top of the cobra RunE.
// Returns nil when ctx carries no Client (opt-out or unreadable
// config); End is nil-safe so callers don't need to branch on the
// return.
//
// See doc.go for the End() defer-direct contract.
func BeginDebug(ctx context.Context) *DebugTx {
	if ClientFromContext(ctx) == nil {
		return nil
	}
	return &DebugTx{}
}

// End finalises the debug transaction: recovers any in-flight panic,
// stamps the emit-side base fields on tx.props, defaults Outcome
// from (recovered panic | ctx.Err() | success), enqueues the
// envelope, and re-panics if the command body panicked.
//
// MUST be called as `defer tx.End(ctx)` directly - see doc.go for
// the load-bearing recover-frame requirement.
func (tx *DebugTx) End(ctx context.Context) {
	r := recover()
	defer func() {
		if r != nil {
			panic(r)
		}
	}()
	if tx == nil {
		return
	}
	c := ClientFromContext(ctx)
	if c == nil {
		return
	}
	stampInvocationBase(&tx.props.Command, &tx.props.DurationMs, &tx.props.Outcome, &tx.props.InvokedBy, &tx.props.InvokedVia, c.startTime, CommandNameDebug, ctx, r)
	c.fireCommandInvoked(tx.props)
}
