// Renders cli/TELEMETRY.md and editors/vscode/TELEMETRY.md plus a small
// intro page through marked, wraps each in notice/template.html, and
// emits src/notice.gen.ts as three named HTML constants.
//
// Each surface's markdown lives next to the code that emits it (cli/,
// editors/vscode/) and is the primary public telemetry contract for
// that surface. The worker serves them at:
//   - /        the intro with links to /cli and /vscode
//   - /cli     the rendered cli/TELEMETRY.md
//   - /vscode  the rendered editors/vscode/TELEMETRY.md
//
// Run by `pnpm run render-notice` (or `just telemetry worker build`).
// Output is gitignored; the worker imports it.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const repoRoot = resolve(root, "../..");

const template = readFileSync(resolve(root, "notice/template.html"), "utf8");

async function render(md: string): Promise<string> {
	const body = await marked.parse(md, { gfm: true, async: true });
	return template.replace("{{content}}", body);
}

const introMd = `# Usage telemetry

Gaffer emits telemetry from two surfaces - the gaffer CLI and the VS Code extension. Each is governed independently by its own opt-outs.

- [Gaffer CLI telemetry notice](/cli)
- [Gaffer VS Code extension telemetry notice](/vscode)
`;

const cliMd = readFileSync(resolve(repoRoot, "cli/TELEMETRY.md"), "utf8");

// The standalone vscode file links to cli/TELEMETRY.md on GitHub so
// the file reads sensibly on its own; rewrite to the worker-internal
// /cli route when serving the rendered page.
const vscodeMd = readFileSync(resolve(repoRoot, "editors/vscode/TELEMETRY.md"), "utf8").replaceAll(
	"https://github.com/kurrent-io/gaffer/tree/main/cli/TELEMETRY.md",
	"/cli",
);

const introHtml = await render(introMd);
const cliHtml = await render(cliMd);
const vscodeHtml = await render(vscodeMd);

const banner = "// Generated by scripts/render-notice.ts. Do not edit by hand.\n";
const output =
	banner +
	`export const introHtml = ${JSON.stringify(introHtml)};\n` +
	`export const cliHtml = ${JSON.stringify(cliHtml)};\n` +
	`export const vscodeHtml = ${JSON.stringify(vscodeHtml)};\n`;

writeFileSync(resolve(root, "src/notice.gen.ts"), output);
console.log("rendered intro + cli/TELEMETRY.md + editors/vscode/TELEMETRY.md -> src/notice.gen.ts");
