// Renders the repo-root TELEMETRY.md through marked, wraps it in
// notice/template.html, and emits src/notice.gen.ts as
// `export const noticeHtml = "..."`.
//
// The markdown lives at the repo root so it's discoverable by anyone
// browsing the source - the worker happens to also serve it as HTML, but
// the file's primary purpose is the public telemetry contract.
//
// Run by `pnpm run render-notice` (or `just telemetry worker build`).
// Output is gitignored; the worker imports it.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const repoRoot = resolve(root, "../..");

const md = readFileSync(resolve(repoRoot, "TELEMETRY.md"), "utf8");
const template = readFileSync(resolve(root, "notice/template.html"), "utf8");

const body = await marked.parse(md, { gfm: true, async: true });
const html = template.replace("{{content}}", body);

const escaped = JSON.stringify(html);
const banner = "// Generated by scripts/render-notice.ts. Do not edit by hand.\n";
const output = `${banner}export const noticeHtml = ${escaped};\n`;

writeFileSync(resolve(root, "src/notice.gen.ts"), output);
console.log("rendered TELEMETRY.md -> src/notice.gen.ts");
