// Renders notice/notice.md through marked, wraps it in template.html, and
// emits src/notice.gen.ts as `export const noticeHtml = "..."`.
//
// Run by `pnpm run render-notice` (or `just telemetry worker build`). Output
// is gitignored; the worker imports it.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const md = readFileSync(resolve(root, "notice/notice.md"), "utf8");
const template = readFileSync(resolve(root, "notice/template.html"), "utf8");

const body = await marked.parse(md, { gfm: true, async: true });
const html = template.replace("{{content}}", body);

const escaped = JSON.stringify(html);
const banner = "// Generated by scripts/render-notice.ts. Do not edit by hand.\n";
const output = `${banner}export const noticeHtml = ${escaped};\n`;

writeFileSync(resolve(root, "src/notice.gen.ts"), output);
console.log("rendered notice/notice.md -> src/notice.gen.ts");
